### ISSUE TITLE
Running the solution -- "loading / unhandled error"

### ISSUE THREAD

**Issue by Jon2226** [Kahan-CS/Conestoga_Connects-Project_IV-Group-7#13]
One important thing to remember: when you run (or debug) solution, always ensure that the Server is the startup project rather than the Client.  Otherwise, the web page will either be stuck on a blank screen that says "Loading..." or show a pale yellow bar at the bottom that says "An unhandled error has occurred.  Reload."

In summary: always make sure to run the Server project before the Client.

**Comment by Kahan-CS** [comment]
I believe we can close as it is not unresolved anymore. This can be added in the documentation
